-- AlterTable
ALTER TABLE `team` MODIFY `position` INTEGER NOT NULL DEFAULT 1,
    MODIFY `wins` INTEGER NOT NULL DEFAULT 0,
    MODIFY `losses` INTEGER NOT NULL DEFAULT 0,
    MODIFY `draws` INTEGER NOT NULL DEFAULT 0,
    MODIFY `points` INTEGER NOT NULL DEFAULT 0,
    MODIFY `matchRecord` VARCHAR(191) NOT NULL DEFAULT '0-0',
    MODIFY `setRecord` VARCHAR(191) NOT NULL DEFAULT '0-0',
    MODIFY `gamesRecord` VARCHAR(191) NOT NULL DEFAULT '0-0',
    MODIFY `history` VARCHAR(191) NOT NULL DEFAULT '';
